// ============================================================================
//  The 6 tournament scenarios.
//
//  Group phases are GENERATED by buildGroupSchedule (verified against the exact
//  hand-given Scenario 1 plan — see schedule.test.ts). KO brackets are built
//  with standard seeded pairings (1v4 / 2v3 for a Top-4, 1v8/4v5/3v6/2v7 for a
//  Top-8). Seeds are filled by qualification.ts at runtime.
//
//  ── HOW TO ADD A NEW SCENARIO ──────────────────────────────────────────────
//  1. Add an entry to the SCENARIO_SPECS array below (sizes, durations,
//     qualification, KO format, KO start/end times).
//  2. That's it — group + KO schedules are generated from the spec.
// ============================================================================

import type {
  GroupDef,
  KoMatchDef,
  KoStage,
  MatchFormat,
  Scenario,
  SlotRef,
} from '../types';
import { addMinutes, buildGroupSchedule, minutesToTime, timeToMinutes } from '../lib/schedule';

const START_TIME = '11:10';
const GAP = 3; // minutes between consecutive matches on a court

// Match formats ---------------------------------------------------------------
const AMERICANO: MatchFormat = { type: 'americano', goldenPoint: true };
const SHORT_SET_4: MatchFormat = { type: 'shortSet', goldenPoint: true, setTarget: 4 };
const BO3_TO_4: MatchFormat = {
  type: 'bestOfSets',
  goldenPoint: true,
  sets: 3,
  setTarget: 4,
  tieBreakTarget: 7,
};
const BO3_TO_6: MatchFormat = {
  type: 'bestOfSets',
  goldenPoint: true,
  sets: 3,
  setTarget: 6,
  tieBreakTarget: 7,
};

// ── Group helpers ────────────────────────────────────────────────────────────
function makeGroups(sizes: number[]): GroupDef[] {
  return sizes.map((size, i) => {
    const n = i + 1;
    return {
      id: `G${n}`,
      label: `Gruppe ${n}`,
      slots: Array.from({ length: size }, (_, j) => `G${n}.${j + 1}`),
    };
  });
}

// ── KO bracket helpers ───────────────────────────────────────────────────────
const seed = (n: number): SlotRef => ({ type: 'seed', seed: n });
const winnerOf = (matchId: string): SlotRef => ({ type: 'winner', matchId });
const loserOf = (matchId: string): SlotRef => ({ type: 'loser', matchId });

/** Build a Top-4 KO: SF1 (1v4), SF2 (2v3), Final, 3rd place (parallel). */
function buildKo4(sfStart: string, sfFormat: MatchFormat, finalStart: string, finalFormat: MatchFormat): KoMatchDef[] {
  return [
    ko('SF1', 'SF', 'Halbfinale 1', sfStart, 1, seed(1), seed(4), sfFormat),
    ko('SF2', 'SF', 'Halbfinale 2', sfStart, 2, seed(2), seed(3), sfFormat),
    ko('F', 'F', 'Finale', finalStart, 1, winnerOf('SF1'), winnerOf('SF2'), finalFormat),
    ko('P3', 'P3', 'Spiel um Platz 3', finalStart, 2, loserOf('SF1'), loserOf('SF2'), finalFormat),
  ];
}

/** Build a Top-8 KO: 4 QFs → 2 SFs → Final + 3rd place. */
function buildKo8(
  qfStart: string,
  qfSlot: number,
  qfFormat: MatchFormat,
  sfStart: string,
  sfFormat: MatchFormat,
  finalStart: string,
  finalFormat: MatchFormat,
): KoMatchDef[] {
  // QFs run two-at-a-time across the 2 courts, two waves.
  const qfWave2 = addMinutes(qfStart, qfSlot + GAP);
  return [
    ko('QF1', 'QF', 'Viertelfinale 1', qfStart, 1, seed(1), seed(8), qfFormat),
    ko('QF2', 'QF', 'Viertelfinale 2', qfStart, 2, seed(4), seed(5), qfFormat),
    ko('QF3', 'QF', 'Viertelfinale 3', qfWave2, 1, seed(2), seed(7), qfFormat),
    ko('QF4', 'QF', 'Viertelfinale 4', qfWave2, 2, seed(3), seed(6), qfFormat),
    ko('SF1', 'SF', 'Halbfinale 1', sfStart, 1, winnerOf('QF1'), winnerOf('QF2'), sfFormat),
    ko('SF2', 'SF', 'Halbfinale 2', sfStart, 2, winnerOf('QF3'), winnerOf('QF4'), sfFormat),
    ko('F', 'F', 'Finale', finalStart, 1, winnerOf('SF1'), winnerOf('SF2'), finalFormat),
    ko('P3', 'P3', 'Spiel um Platz 3', finalStart, 2, loserOf('SF1'), loserOf('SF2'), finalFormat),
  ];
}

function ko(
  id: string,
  stage: KoStage,
  label: string,
  time: string,
  court: 1 | 2,
  home: SlotRef,
  away: SlotRef,
  format: MatchFormat,
): KoMatchDef {
  return { id, kind: 'ko', stage, label, time, court, home, away, format };
}

// ── Scenario specifications ──────────────────────────────────────────────────
interface ScenarioSpec {
  id: number;
  name: string;
  description: string;
  groupSizes: number[];
  groupDuration: number;
  qualification: Scenario['qualification'];
  endTime: string;
  koSummary: string;
  /** builds the KO bracket given the computed group-phase end time. */
  buildKo: (groupEnd: string) => KoMatchDef[];
}

const SCENARIO_SPECS: ScenarioSpec[] = [
  {
    id: 1,
    name: '16 Teams · Top 4',
    description: '16 Teams, 4 Vierergruppen. Nur die Gruppensieger ziehen ins Halbfinale ein.',
    groupSizes: [4, 4, 4, 4],
    groupDuration: 10,
    qualification: { topPerGroup: 1, qualifierCount: 4 },
    endTime: '15:42',
    koSummary: 'Halbfinale & Finale: Best-of-3, Sätze bis 6, Match-Tie-Break bis 7.',
    buildKo: (groupEnd) => buildKo4(addMinutes(groupEnd, GAP), BO3_TO_6, '14:44', BO3_TO_6),
  },
  {
    id: 2,
    name: '16 Teams · Top 8',
    description: '16 Teams, 4 Vierergruppen. Die besten 2 jeder Gruppe erreichen das Viertelfinale.',
    groupSizes: [4, 4, 4, 4],
    groupDuration: 10,
    qualification: { topPerGroup: 2, qualifierCount: 8 },
    endTime: '15:40',
    koSummary: 'Viertelfinale: 1 Kurzsatz bis 4. Ab Halbfinale: Best-of-3 bis 4, MTB bis 7.',
    buildKo: (groupEnd) => {
      const qfStart = addMinutes(groupEnd, GAP);
      const sfStart = addMinutes(qfStart, 2 * (16 + GAP));
      const finalStart = addMinutes(sfStart, 36 + GAP);
      return buildKo8(qfStart, 16, SHORT_SET_4, sfStart, BO3_TO_4, finalStart, BO3_TO_4);
    },
  },
  {
    id: 3,
    name: '14 Teams · Top 4',
    description: '14 Teams, zwei Vierer- und zwei Dreiergruppen. Nur Gruppensieger ziehen weiter.',
    groupSizes: [4, 4, 3, 3],
    groupDuration: 15,
    qualification: { topPerGroup: 1, qualifierCount: 4 },
    endTime: '15:48',
    koSummary: 'Halbfinale & Finale: Best-of-3, Sätze bis 6, Match-Tie-Break bis 7.',
    buildKo: (groupEnd) => {
      const sfStart = addMinutes(groupEnd, GAP);
      const finalStart = addMinutes(sfStart, 55 + GAP);
      return buildKo4(sfStart, BO3_TO_6, finalStart, BO3_TO_6);
    },
  },
  {
    id: 4,
    name: '14 Teams · Top 8',
    description: '14 Teams, zwei Vierer- und zwei Dreiergruppen. Top 2 je Gruppe ins Viertelfinale.',
    groupSizes: [4, 4, 3, 3],
    groupDuration: 11,
    qualification: { topPerGroup: 2, qualifierCount: 8 },
    endTime: '15:48',
    koSummary: 'Viertelfinale, Halbfinale & Finale: Best-of-3 bis 4, MTB bis 7.',
    buildKo: (groupEnd) => {
      const qfStart = addMinutes(groupEnd, GAP);
      const sfStart = addMinutes(qfStart, 2 * (35 + GAP));
      const finalStart = addMinutes(sfStart, 35 + GAP);
      return buildKo8(qfStart, 35, BO3_TO_4, sfStart, BO3_TO_4, finalStart, BO3_TO_4);
    },
  },
  {
    id: 5,
    name: '12 Teams · Top 4',
    description: '12 Teams, 3 Vierergruppen. 3 Gruppensieger plus der beste Gruppenzweite.',
    groupSizes: [4, 4, 4],
    groupDuration: 15,
    qualification: { topPerGroup: 1, bestRunnersUp: 1, bestRunnersUpRank: 2, qualifierCount: 4 },
    endTime: '15:48',
    koSummary: 'Halbfinale & Finale: Best-of-3, Sätze bis 6, Match-Tie-Break bis 7.',
    buildKo: (groupEnd) => {
      const sfStart = addMinutes(groupEnd, GAP);
      const finalStart = addMinutes(sfStart, 55 + GAP);
      return buildKo4(sfStart, BO3_TO_6, finalStart, BO3_TO_6);
    },
  },
  {
    id: 6,
    name: '12 Teams · Top 8',
    description: '12 Teams, 3 Vierergruppen. Top 2 je Gruppe plus die 2 besten Dritten.',
    groupSizes: [4, 4, 4],
    groupDuration: 11,
    qualification: { topPerGroup: 2, bestRunnersUp: 2, bestRunnersUpRank: 3, qualifierCount: 8 },
    endTime: '15:48',
    koSummary: 'Viertelfinale, Halbfinale & Finale: Best-of-3 bis 4, MTB bis 7.',
    // Timings match the organiser's exact reference plan: QF 13:16, SF 14:32,
    // Finale 15:10 — each a 35-minute slot.
    buildKo: (groupEnd) => {
      const qfStart = addMinutes(groupEnd, GAP); // 13:13 + 3 = 13:16
      const sfStart = addMinutes(qfStart, 2 * (35 + GAP)); // two QF waves → 14:32
      const finalStart = addMinutes(sfStart, 35 + GAP); // 15:10
      return buildKo8(qfStart, 35, BO3_TO_4, sfStart, BO3_TO_4, finalStart, BO3_TO_4);
    },
  },
];

// ── Assemble the scenarios ───────────────────────────────────────────────────
function buildScenario(spec: ScenarioSpec): Scenario {
  const groups = makeGroups(spec.groupSizes);
  const groupSchedule = buildGroupSchedule(groups, START_TIME, spec.groupDuration, AMERICANO, GAP);

  // group phase end = latest start + match duration
  const lastStart = groupSchedule.reduce(
    (max, m) => Math.max(max, timeToMinutes(m.time)),
    timeToMinutes(START_TIME),
  );
  const groupEnd = minutesToTime(lastStart + spec.groupDuration);

  return {
    id: spec.id,
    name: spec.name,
    description: spec.description,
    teamCount: spec.groupSizes.reduce((a, b) => a + b, 0),
    groups,
    groupMatchDurationMin: spec.groupDuration,
    qualification: spec.qualification,
    groupSchedule,
    koSchedule: spec.buildKo(groupEnd),
    endTime: spec.endTime,
    koSummary: spec.koSummary,
  };
}

export const SCENARIOS: Scenario[] = SCENARIO_SPECS.map(buildScenario);

export function getScenario(id: number): Scenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}
